### ISSUE TITLE
Support of english

### ISSUE THREAD

**Issue by martinratinaud** [Mitica/quote-parser-js#1]
Hi guys,

this is a nice tool I would use but there is no support for english, do you plan on supporting it ? (and french BTW)

Thanks again

**Comment by mitica** [comment]
Hi @martinratinaud,

I added English support for double quotes. ("text") and only 4 verbs: ['said', 'added', 'wrote', 'told'].
If you'l need better support write an issue.

**Comment by martinratinaud** [comment]
Thanks a lot. But I tried it this way with no success

```
var $ = require('cheerio');
var parser = require('quote-parser');
var request = require('request');

request('http://fourhourworkweek.com/blog/', function (error, response, body) {
  var t,
      quotes;

  if (!error && response.statusCode == 200) {
    t = $.load(body)("body");
    quotes = parser.parse(t.text(), 'en');
    console.log(quotes); //eslint-disable-line
  }
});
```

Is it supposed to work this way ?

**Comment by mitica** [comment]
Now it will work for your example, but be careful on non-break-spaces. **cheerio** doesn't replace NBSP with SPACE.

Current version(0.1.2) is not working properly with NBSP.

**Comment by martinratinaud** [comment]
Awesome, it works quite well, thanks a lot !

**Comment by martinratinaud** [comment]
Well, it also does not work on this page.

Cheers

**Comment by mitica** [comment]
Now (v0.1.3) it works well with Non-breaking spaces.
I've added a test for that [page](http://fourhourworkweek.com/blog/). It finds 4 quotes.

Cheers

**Comment by martinratinaud** [comment]
Hi Dumitru, for information, I just released a chrome extension that uses your parser. Check it out and tell me what you think.

http://www.pikilabs.com/en/

Thanks again for your work 
Cheers

**Comment by mitica** [comment]
Hi Martin, I'm glad I could help.
Thanks for mentioning my library, you don't need to.

For information, see http://www.entipic.com/help - for ideas.

**Comment by martinratinaud** [comment]
Thanks for this I'll add it in next release. Do you have a twitter so that we can chat a bit Mine is https://twitter.com/martinratinaud

Cheers
